// Code generated by scripts/generate-desktop-contract.mjs. DO NOT EDIT.

package desktopcontract

type DesktopApiError struct {
	Code       string `json:"code"`
	Message    string `json:"message"`
	Details    any    `json:"details"`
	RequestId  string `json:"requestId"`
	Retryable  bool   `json:"retryable"`
	RetryAfter *int   `json:"retryAfter"`
}

type DesktopMaintenanceState struct {
	Active     bool    `json:"active"`
	Message    *string `json:"message"`
	RetryAfter *int    `json:"retryAfter"`
}

type DesktopCapabilitiesLimits struct {
	MaxJsonRequestBytes        int `json:"maxJsonRequestBytes"`
	MaxJsonResponseBytes       int `json:"maxJsonResponseBytes"`
	MaxAttachmentUploadBytes   int `json:"maxAttachmentUploadBytes"`
	MaxAttachmentDownloadBytes int `json:"maxAttachmentDownloadBytes"`
}

type DesktopSyncCapabilities struct {
	ProtocolVersion int      `json:"protocolVersion"`
	Providers       []string `json:"providers"`
	Incremental     bool     `json:"incremental"`
	CursorReset     bool     `json:"cursorReset"`
}

type DesktopCapabilities struct {
	ApiVersion           string                    `json:"apiVersion"`
	MinimumClientVersion string                    `json:"minimumClientVersion"`
	LatestClientVersion  string                    `json:"latestClientVersion"`
	Features             map[string]bool           `json:"features"`
	Limits               DesktopCapabilitiesLimits `json:"limits"`
	Sync                 DesktopSyncCapabilities   `json:"sync"`
	Maintenance          DesktopMaintenanceState   `json:"maintenance"`
}

type DesktopSessionUser struct {
	Id            int64  `json:"id"`
	Username      string `json:"username"`
	Administrator bool   `json:"administrator"`
}

type DesktopSessionCreateRequest struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	DeviceId   string `json:"deviceId"`
	DeviceName string `json:"deviceName"`
}

type DesktopSessionMigrateRequest struct {
	DeviceId   string `json:"deviceId"`
	DeviceName string `json:"deviceName"`
}

type DesktopSessionRefreshRequest struct {
	RefreshToken string `json:"refreshToken"`
}

type DesktopSessionResponse struct {
	AccessToken      string             `json:"accessToken"`
	RefreshToken     string             `json:"refreshToken"`
	TokenType        string             `json:"tokenType"`
	ExpiresIn        int                `json:"expiresIn"`
	RefreshExpiresAt string             `json:"refreshExpiresAt"`
	DeviceId         string             `json:"deviceId"`
	User             DesktopSessionUser `json:"user"`
}

type DesktopDeviceSummary struct {
	DeviceId      string  `json:"deviceId"`
	DeviceName    string  `json:"deviceName"`
	ClientVersion string  `json:"clientVersion"`
	CreatedAt     string  `json:"createdAt"`
	LastUsedAt    string  `json:"lastUsedAt"`
	ExpiresAt     string  `json:"expiresAt"`
	RevokedAt     *string `json:"revokedAt"`
	Current       bool    `json:"current"`
}

type DesktopDeviceListResponse struct {
	Devices []DesktopDeviceSummary `json:"devices"`
}

type DesktopSyncProviderRef struct {
	GraphId     *string `json:"graphId"`
	DeltaScope  *string `json:"deltaScope"`
	Folder      *string `json:"folder"`
	UidValidity *int64  `json:"uidValidity"`
	Uid         *int64  `json:"uid"`
	ModSequence *int64  `json:"modSequence"`
}

type DesktopSyncChange struct {
	Id             string                 `json:"id"`
	Kind           string                 `json:"kind"`
	ChangeType     string                 `json:"changeType"`
	Provider       string                 `json:"provider"`
	Folder         string                 `json:"folder"`
	PreviousFolder *string                `json:"previousFolder"`
	ProviderRef    DesktopSyncProviderRef `json:"providerRef"`
	BodyVersion    *string                `json:"bodyVersion"`
	Payload        map[string]any         `json:"payload"`
}

type DesktopSyncChangesResponse struct {
	Upserts             []DesktopSyncChange `json:"upserts"`
	DeletedIds          []string            `json:"deletedIds"`
	NextCursor          string              `json:"nextCursor"`
	HasMore             bool                `json:"hasMore"`
	UnreadCount         int                 `json:"unreadCount"`
	ServerTime          string              `json:"serverTime"`
	CursorResetRequired bool                `json:"cursorResetRequired"`
	ErrorCode           *string             `json:"errorCode"`
	Provider            string              `json:"provider"`
	LastSyncAt          *string             `json:"lastSyncAt"`
}

type DesktopUnreadFolderSummary struct {
	Folder      string `json:"folder"`
	UnreadCount int    `json:"unreadCount"`
	TotalCount  int    `json:"totalCount"`
}

type DesktopUnreadAccountSummary struct {
	AccountId   int64                        `json:"accountId"`
	Provider    string                       `json:"provider"`
	UnreadCount int                          `json:"unreadCount"`
	Folders     []DesktopUnreadFolderSummary `json:"folders"`
	ErrorCode   *string                      `json:"errorCode"`
}

type DesktopUnreadSummaryResponse struct {
	Accounts   []DesktopUnreadAccountSummary `json:"accounts"`
	ServerTime string                        `json:"serverTime"`
}
