// Code generated by scripts/generate-desktop-contract.mjs. DO NOT EDIT.

package desktopcontract

type DesktopApiError struct {
	Code       string `json:"code"`
	Message    string `json:"message"`
	Details    any    `json:"details"`
	RequestId  string `json:"requestId"`
	Retryable  bool   `json:"retryable"`
	RetryAfter *int   `json:"retryAfter"`
}

type DesktopMaintenanceState struct {
	Active     bool    `json:"active"`
	Message    *string `json:"message"`
	RetryAfter *int    `json:"retryAfter"`
}

type DesktopCapabilitiesLimits struct {
	MaxJsonRequestBytes        int `json:"maxJsonRequestBytes"`
	MaxJsonResponseBytes       int `json:"maxJsonResponseBytes"`
	MaxAttachmentUploadBytes   int `json:"maxAttachmentUploadBytes"`
	MaxAttachmentDownloadBytes int `json:"maxAttachmentDownloadBytes"`
}

type DesktopSyncCapabilities struct {
	ProtocolVersion int      `json:"protocolVersion"`
	Providers       []string `json:"providers"`
	Incremental     bool     `json:"incremental"`
	CursorReset     bool     `json:"cursorReset"`
}

type DesktopCapabilities struct {
	ApiVersion           string                    `json:"apiVersion"`
	MinimumClientVersion string                    `json:"minimumClientVersion"`
	LatestClientVersion  string                    `json:"latestClientVersion"`
	Features             map[string]bool           `json:"features"`
	Limits               DesktopCapabilitiesLimits `json:"limits"`
	Sync                 DesktopSyncCapabilities   `json:"sync"`
	Maintenance          DesktopMaintenanceState   `json:"maintenance"`
}

type DesktopSessionUser struct {
	Id            int64  `json:"id"`
	Username      string `json:"username"`
	Administrator bool   `json:"administrator"`
}

type DesktopSessionCreateRequest struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	DeviceId   string `json:"deviceId"`
	DeviceName string `json:"deviceName"`
}

type DesktopSessionMigrateRequest struct {
	DeviceId   string `json:"deviceId"`
	DeviceName string `json:"deviceName"`
}

type DesktopSessionRefreshRequest struct {
	RefreshToken string `json:"refreshToken"`
}

type DesktopSessionResponse struct {
	AccessToken      string             `json:"accessToken"`
	RefreshToken     string             `json:"refreshToken"`
	TokenType        string             `json:"tokenType"`
	ExpiresIn        int                `json:"expiresIn"`
	RefreshExpiresAt string             `json:"refreshExpiresAt"`
	DeviceId         string             `json:"deviceId"`
	User             DesktopSessionUser `json:"user"`
}

type DesktopDeviceSummary struct {
	DeviceId      string  `json:"deviceId"`
	DeviceName    string  `json:"deviceName"`
	ClientVersion string  `json:"clientVersion"`
	CreatedAt     string  `json:"createdAt"`
	LastUsedAt    string  `json:"lastUsedAt"`
	ExpiresAt     string  `json:"expiresAt"`
	RevokedAt     *string `json:"revokedAt"`
	Current       bool    `json:"current"`
}

type DesktopDeviceListResponse struct {
	Devices []DesktopDeviceSummary `json:"devices"`
}
