// Generated by scripts/generate-desktop-contract.mjs. Do not edit.

export interface DesktopApiError {
  code: string;
  message: string;
  details: unknown;
  requestId: string;
  retryable: boolean;
  retryAfter: number | null;
}

export interface DesktopMaintenanceState {
  active: boolean;
  message: string | null;
  retryAfter: number | null;
}

export interface DesktopCapabilitiesLimits {
  maxJsonRequestBytes: number;
  maxJsonResponseBytes: number;
  maxAttachmentUploadBytes: number;
  maxAttachmentDownloadBytes: number;
}

export interface DesktopSyncCapabilities {
  protocolVersion: number;
  providers: string[];
  incremental: boolean;
  cursorReset: boolean;
}

export interface DesktopCapabilities {
  apiVersion: string;
  minimumClientVersion: string;
  latestClientVersion: string;
  features: Record<string, boolean>;
  limits: DesktopCapabilitiesLimits;
  sync: DesktopSyncCapabilities;
  maintenance: DesktopMaintenanceState;
}

export interface DesktopSessionUser {
  id: number;
  username: string;
  administrator: boolean;
}

export interface DesktopSessionCreateRequest {
  email: string;
  password: string;
  deviceId: string;
  deviceName: string;
}

export interface DesktopSessionMigrateRequest {
  deviceId: string;
  deviceName: string;
}

export interface DesktopSessionRefreshRequest {
  refreshToken: string;
}

export interface DesktopSessionResponse {
  accessToken: string;
  refreshToken: string;
  tokenType: string;
  expiresIn: number;
  refreshExpiresAt: string;
  deviceId: string;
  user: DesktopSessionUser;
}

export interface DesktopDeviceSummary {
  deviceId: string;
  deviceName: string;
  clientVersion: string;
  createdAt: string;
  lastUsedAt: string;
  expiresAt: string;
  revokedAt: string | null;
  current: boolean;
}

export interface DesktopDeviceListResponse {
  devices: DesktopDeviceSummary[];
}

export interface DesktopSyncProviderRef {
  graphId: string | null;
  deltaScope: string | null;
  folder: string | null;
  uidValidity: number | null;
  uid: number | null;
  modSequence: number | null;
}

export interface DesktopSyncChange {
  id: string;
  kind: string;
  changeType: string;
  provider: string;
  folder: string;
  previousFolder: string | null;
  providerRef: DesktopSyncProviderRef;
  bodyVersion: string | null;
  payload: Record<string, unknown>;
}

export interface DesktopSyncChangesResponse {
  upserts: DesktopSyncChange[];
  deletedIds: string[];
  nextCursor: string;
  hasMore: boolean;
  unreadCount: number;
  serverTime: string;
  cursorResetRequired: boolean;
  errorCode: string | null;
  provider: string;
  lastSyncAt: string | null;
}

export interface DesktopUnreadFolderSummary {
  folder: string;
  unreadCount: number;
  totalCount: number;
}

export interface DesktopUnreadAccountSummary {
  accountId: number;
  provider: string;
  unreadCount: number;
  folders: DesktopUnreadFolderSummary[];
  errorCode: string | null;
}

export interface DesktopUnreadSummaryResponse {
  accounts: DesktopUnreadAccountSummary[];
  serverTime: string;
}

